/**
 * Kupyna WASM Module Type Definitions
 * Generated by Emscripten with -sMODULARIZE=1 -sEXPORT_ES6=1
 */

export interface KupynaWasmModule extends EmscriptenModule {
  // Memory management
  _malloc(size: number): number;
  _free(ptr: number): void;

  // Kupyna hash functions
  _kupyna_alloc(): number;
  _kupyna_init(ctx: number, hashLen: number): number;
  _kupyna_update(ctx: number, data: number, len: number): number;
  _kupyna_final(ctx: number, hash: number): number;
  _kupyna_free(ctx: number): void;
  _kupyna_hash(data: number, len: number, hash: number, hashLen: number): number;

  // Runtime methods
  ccall: typeof ccall;
  cwrap: typeof cwrap;
  getValue(ptr: number, type: string): number;
  setValue(ptr: number, value: number, type: string): void;
  UTF8ToString(ptr: number, maxBytesToRead?: number): string;
  stringToUTF8(str: string, outPtr: number, maxBytesToWrite: number): void;

  // Memory views
  HEAP8: Int8Array;
  HEAP16: Int16Array;
  HEAP32: Int32Array;
  HEAPU8: Uint8Array;
  HEAPU16: Uint16Array;
  HEAPU32: Uint32Array;
  HEAPF32: Float32Array;
  HEAPF64: Float64Array;
}

export interface EmscriptenModule {
  print?: (text: string) => void;
  printErr?: (text: string) => void;
  locateFile?: (url: string, scriptDirectory: string) => string;
  onRuntimeInitialized?: () => void;
  onAbort?: (what: string | Error) => void;
}

export type KupynaModuleFactory = (
  moduleOverrides?: Partial<EmscriptenModule>
) => Promise<KupynaWasmModule>;

// Emscripten ccall/cwrap types
export function ccall(
  ident: string,
  returnType: string | null,
  argTypes: string[],
  args: unknown[],
  opts?: { async?: boolean }
): unknown;

export function cwrap(
  ident: string,
  returnType: string | null,
  argTypes: string[]
): (...args: unknown[]) => unknown;

// Error codes from native/include/kupyna.h
export enum KupynaErrorCode {
  OK = 0,
  ERROR_NULL_POINTER = -1,
  ERROR_INVALID_HASH_LEN = -2,
  ERROR_NOT_INITIALIZED = -3,
  ERROR_MEMORY = -4,
}

// Supported hash sizes in bytes
export type KupynaHashSize = 32 | 48 | 64;

// Map hash size to bit size
export const HASH_SIZE_BITS: Record<KupynaHashSize, number> = {
  32: 256,
  48: 384,
  64: 512,
};
